### ISSUE TITLE
pip install ocrmac not working

### ISSUE THREAD

**Issue by imsomdev** [straussmaximilian/ocrmac#12]
```
  Downloading ocrmac-0.1.6-py2.py3-none-any.whl (7.6 kB)
Requirement already satisfied: pillow in ./venv/lib/python3.10/site-packages (from ocrmac) (10.2.0)
Collecting pyobjc-framework-Vision
  Downloading pyobjc-framework-Vision-10.1.tar.gz (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.4/125.4 KB 1.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Passport Verification/passport/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Passport Verification/passport/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/media/somdev/84AE09BCAE09A82E/SentientGeeks/SentientGeeks/Passport Verification/passport/venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-6s2194fb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-6s2194fb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-6s2194fb/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 26, in <module>
        File "/tmp/pip-install-pze_od4e/pyobjc-framework-vision_6efa58eb6a744cd9afa78447ad149e4b/pyobjc_setup.py", line 517, in Extension
          lines = subprocess.check_output(["xcodebuild", "-version"], text=True).splitlines()
        File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'xcodebuild'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by straussmaximilian** [comment]
Looks like there are problems installing the underlying dependency `pyobjc-framework-Vision`. Are you using a mac system?

**Comment by imsomdev** [comment]
Ohh, I am using linux. Sorry for the inconvenience.
